### ISSUE TITLE
Type-ahead selection only works with initial character

### ISSUE THREAD

**Issue by sronsiek** [fnagel/jquery-ui#339]
Assume an alphabetically sorted option list with many items, multiple items beginning with 'M', incl one named 'Medium'.

Standard browser behaviour allows type-ahead (in quick succession) of a number of chars, eg 'med' and the element beginning with this string will be selected eg 'Medium'.

In selectmenu the same action results in selection of the first item beginning with 'm' - then selection of the first item starting with 'e' and finally selection of the first item beginning with 'd'.

Hence the plugin does not reflect standard browser behaviour.

**Comment by fnagel** [comment]
Did you test the latest dev version? I've just pushed a fix for this behavior, see #337

**Comment by sronsiek** [comment]
I have tested on http://jsfiddle.net/3BuK2/2/ and confirm that type-ahead selection works in principle, but there is still an issue related to timeouts.

In the 'lengthened' jsfiddle menu containing all the extra options beginning with 'B', click to open the drop-down. Now hit the following keys at approx half second intervals:

b b b b a a a a

As expected, the selection starts with the first option beginning with b, and cycles through the remaining options starting with b. However when the first 'non-b' char is hit, the selection remains frozen.

If I wait a couple of seconds - normal service is resumed - typing 'a' jumps to the first 'a' selection.

**Comment by fnagel** [comment]
This behavior seems not to be related with #339 nor #332. Please open a new issue for that.

Anyway: I guess that the expected behavior for the current implementation. With the key codes above you are basically searching for a word with "bbbba" which wont be found as its not existing in the select. At least in FF this is the native select behavior.

Can you give me a real world example why this is a issue? It seems the above used key order is a theoretical one.
I have no idea how to fix this but to rework the whole typeahead functionality.

**Comment by sronsiek** [comment]
The initial issue for this ticket is solved, the remaining issue from my previous comment has been raised as  #341.

This ticket can be closed.

**Comment by sronsiek** [comment]
Closing as per prev comment.
