### ISSUE TITLE
focusing by trigger (focus) on original select does not work

### ISSUE THREAD

**Issue by keizie** [fnagel/jquery-ui#66]
```
146                 // change event on original selectmenu
147                 this.element
148                         .bind("click.selectmenu", function() {
149                                 self._refreshValue();
150                         })
151                         // newelement can be null under unclear circumstances in IE8
152                         .bind("focus.selectmenu", function() {
153                                 if (this.newelement) {
154                                         this.newelement[0].focus();
155                                 }
156                         });
```

With routine above, `$('original select').trigger('focus.selectmenu')` never give focus to generated dropdown element, 'cause `this` inside callback set to select element scope, not jquery object.
So `this` statement should be replaced with `self`, then things works.

**Comment by fnagel** [comment]
Please note this widget was not originally created by me.

I would agree that inside a callback self should be used, but as this is a work around for IE8 (see comment) this problem is reproducible in IE8 only?

**Comment by keizie** [comment]
The callback routine itself is not IE8-only.
The comment explains why block nested with `if`, I think.

**Comment by fnagel** [comment]
Ahhh the comment in the code is just a hint, a ToDo.As I not developed this widget initially and some comments are confusing.

Would you please tell me how to test this, so I can test your patch?

**Comment by keizie** [comment]
Before patch, $('select').focus() or .trigger('focus') don't give focus to selectmenu widget.
After patch, you can get selectmenu widget focused by focusing original select element.

**Comment by fnagel** [comment]
Thanks again for reporting. This issue is fixed, please reopen if necessary.

**Comment by beatlevic** [comment]
Maybe it is related, but I still get an error in IE8 when I put a select => true on one of the hidden items. 

Message: Can't move focus to the control because it is invisible, not enabled, or of a type that does not accept the focus.

Any suggestions?

**Comment by fnagel** [comment]
PN form beatlevic: 
I am currently getting an error in IE8 when I put a selected => true on one of the 'hidden' items. When I don't put a selected on one of the items, the select menu does show without any errors.
Message: Can't move focus to the control because it is invisible, not enabled, or of a type that does not accept the focus.
Any suggestions? Thanks.

BTW I fixed it for now by removing .focus() in the open function.
.find('li:not(.' + self.widgetBaseClass + '-group):eq(' + this._selectedIndex() + ') a')[0];//.focus();

**Comment by fnagel** [comment]
@beatlevic
There has been some changes so would you please test if this error still occurs when using this version: https://github.com/fnagel/jquery-ui/zipball/selectmenu_v1.1.0 or latest version

This could be related: https://github.com/fnagel/jquery-ui/pull/94

**Comment by fnagel** [comment]
Please give feedback!

**Comment by beatlevic** [comment]
Unfortunately I'm no longer on the project to retest the new version. So I'm
afraid I can't provide you with useful feedback. Anyway thank for your
efforts, and keep up the good work.

Cheers,
Coen

On Thu, Jun 16, 2011 at 10:46 PM, fnagel <
reply@reply.github.com>wrote:

> Please give feedback!
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fnagel/jquery-ui/issues/66#issuecomment-1384145

## 

Coen Stevens
Freelancer - http://BeatleTech.com

Follow me on Twitter: @beatlevic
Skype: beatlevic
Tel: +31 6 24 67 63 49

Linkedin: http://www.linkedin.com/in/beatlevic

**Comment by fnagel** [comment]
Thanks for your response. I will close this issue as Im not able to reproduce this issue atm. Please reopen if needed.
